services:
  # .NET API Backend
  iq-test-api:
    build:
      context: ./IqTestApi
      dockerfile: Dockerfile
    ports:
      - "7210:7210"
      - "5263:5263"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:7210;http://0.0.0.0:5263
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./IqTestApi:/app
      - /app/bin
      - /app/obj
      - ~/.dotnet/https:/https:ro
    networks:
      - iq-network

  # Angular Frontend
  iq-test-frontend:
    build:
      context: ./iq-test-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./iq-test-frontend:/app
      - /app/node_modules
    depends_on:
      - iq-test-api
    networks:
      - iq-network

networks:
  iq-network:
    driver: bridge
