name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: sudo dotnet restore IqTestApi/IqTestApi.csproj

    - name: Build
      run: sudo dotnet build IqTestApi/IqTestApi.csproj --no-restore

  test-frontend:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: iq-test-frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd iq-test-frontend
        sudo npm ci

    - name: Build
      run: |
        cd iq-test-frontend
        sudo npm run build

  docker-build:
    runs-on: self-hosted
    needs: [test-api, test-frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Docker Compose
      run: sudo docker-compose config
